exclude: [Gemfile, Gemfile.lock, Procfile, vendor, gems, README.md]

sitename:  Foreman
tagline: Foreman is a complete lifecycle management tool for physical and virtual servers.
description: Foreman is an open source project that gives system administrators the power to easily automate repetitive tasks, quickly deploy applications, and proactively manage servers, on-premises or in the cloud.

production_url : http://theforeman.org
url: http://theforeman.org
baseurl: "" #keep at "" for the Atom feed
foreman_version: '1.22'

paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
permalink: /:year/:month/:title.html
blogname: Foreman Blog
blogdesc: News, notes and noise from around the Foreman community

safe:        false

future:      false
highlighter: rouge
markdown:    kramdown

# this is a hack to allow Sphinx generated docs for foreman-ansible-modules
# be included inside the Jekyll site
include:
- _static

navigation:
  - title: Get Started
    sublinks:
      - title: Features
        url: /introduction.html
      - title: Who uses Foreman
        url: /who_uses.html
      - title: Quickstart
        url: /manuals/latest/quickstart_guide.html
      - title: Sponsors
        url: /sponsors.html
  - title: Get Help
    sublinks:
      - title: Manual
        url: /manuals/latest/index.html
      - title: Plugins
        url: /plugins/
      - title: API docs
        url: /api/latest/index.html
      - title: Training
        url: /training.html
      - title: Support
        url: /support.html
  - title: Get involved
    sublinks:
      - title: Community
        url: https://community.theforeman.org
      - title: Report bug
        url: https://projects.theforeman.org/projects
      - title: Contribute
        url: /contribute.html
  - title: News
    sublinks:
      - title: Blog
        url: /blog/index.html
      - title: Events
        url: https://theforeman.org/events
      - title: Videos
        url: /media.html
      - title: Security
        url: /security.html

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
