exclude: [Gemfile, Gemfile.lock, Procfile, vendor, gems, README.md]

sitename:  Foreman
tagline: Foreman is a complete lifecycle management tool for physical and virtual servers.
description: Foreman is an open source project that gives system administrators the power to easily automate repetitive tasks, quickly deploy applications, and proactively manage servers, on-premises or in the cloud.

production_url : http://theforeman.org
url: http://theforeman.org
baseurl: /

safe:        false

future:      false
pygments:    true
markdown:    rdiscount

navigation:
- text: Introduction
  url: introduction.html
- text: Quickstart
  url: manuals/1.9/quickstart_guide.html#QuickstartGuide
- text: Documentation
  url: documentation.html
- text: Community
  url: contribute.html
- text: Videos
  url: media.html
