exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

sitename:  The Foreman
tagline: A single address for server lifecycle management.

production_url : http://theforeman.org
url: http://theforeman.org

safe:        false
auto:        false

future:      false
pygments:    true
markdown:    rdiscount

navigation:
- text: About
  url: about.html
- text: Installation
  url: getting-started.html
- text: Screenshots & Screencasts
  url: media.html
- text: Contribute
  url: contribute.html
- text: Support
  url: support.html
